name: Documentation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  docs:
    name: Build Documentation
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        version: "latest"
    
    - name: Set up Python
      run: uv python install 3.10
    
    - name: Install dependencies
      run: |
        uv sync --group dev
        uv add --dev sphinx sphinx-rtd-theme
    
    - name: Validate README
      run: |
        python -c "
        import laneful
        print('✓ Package can be imported')
        print(f'Version: {laneful.__version__}')
        print(f'Available clients: {laneful.get_available_clients()}')
        "
    
    - name: Validate package metadata
      run: |
        uv run python -c "
        import pkg_resources
        dist = pkg_resources.get_distribution('laneful-python')
        print(f'✓ Package metadata valid: {dist.project_name} {dist.version}')
        "
